//! Native tests for the JSON the plugin hands back to Typst.

use serde_json::Value as Json;
use typst_exif_plugin::read_exif;

fn parse(name: &str, options: &str) -> Json {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/assets/");
    let data = std::fs::read(format!("{path}{name}")).expect("fixture is generated by mkfixtures");
    serde_json::from_slice(&read_exif(&data, options.as_bytes())).expect("plugin returns JSON")
}

#[test]
fn reads_the_jpeg_fixture() {
    let out = parse("sample.jpg", "");
    assert_eq!(out["ok"], true);
    assert_eq!(out["format"], "jpeg");
    assert_eq!(out["tags"]["Make"], "Typst");
    assert_eq!(out["tags"]["Model"], "Exif Fixture Camera");
    assert_eq!(out["tags"]["Orientation"], 1);
    assert_eq!(out["tags"]["PixelXDimension"], 16);
    assert_eq!(out["warnings"].as_array().unwrap().len(), 0);
    assert_eq!(out["count"], 19);
}

#[test]
fn reads_the_png_fixture() {
    let out = parse("sample.png", "");
    assert_eq!(out["ok"], true);
    assert_eq!(out["format"], "png");
    assert_eq!(out["tags"]["Make"], "Typst");
}

#[test]
fn rationals_become_numbers_and_keep_their_fraction_in_display() {
    let out = parse("sample.jpg", "");
    assert_eq!(out["tags"]["ExposureTime"], 1.0 / 200.0);
    assert_eq!(out["display"]["ExposureTime"], "1/200 s");
    assert_eq!(out["tags"]["FNumber"], 2.8);
}

#[test]
fn multi_valued_fields_stay_arrays() {
    let out = parse("sample.jpg", "");
    let latitude = out["tags"]["GPSLatitude"]
        .as_array()
        .expect("three rationals");
    assert_eq!(latitude.len(), 3);
    assert_eq!(latitude[0], 48.0);
    assert_eq!(out["tags"]["GPSLatitudeRef"], "N");
}

#[test]
fn fields_carry_their_ifd_and_type() {
    let out = parse("sample.jpg", "");
    let fields = out["fields"].as_array().unwrap();
    let make = fields.iter().find(|f| f["tag"] == "Make").unwrap();
    assert_eq!(make["ifd"], "primary");
    assert_eq!(make["type"], "ascii");
    assert_eq!(make["count"], 1);
    assert!(make["description"].is_string());

    let gps = fields.iter().find(|f| f["tag"] == "GPSLatitude").unwrap();
    assert_eq!(gps["ifd"], "gps");
    assert_eq!(gps["count"], 3);

    assert_eq!(out["ifds"]["gps"]["GPSLongitudeRef"], "E");
    assert_eq!(
        out["ifds"]["exif"]["DateTimeOriginal"],
        "2024:05:17 09:30:00"
    );
}

#[test]
fn max_values_truncates_long_fields() {
    let out = parse("sample.jpg", r#"{"max_values": 2}"#);
    let gps = out["fields"]
        .as_array()
        .unwrap()
        .iter()
        .find(|f| f["tag"] == "GPSLatitude")
        .unwrap()
        .clone();
    assert_eq!(gps["value"].as_array().unwrap().len(), 2);
    assert_eq!(gps["count"], 3);
    assert_eq!(gps["truncated"], true);
}

#[test]
fn max_display_truncates_long_strings() {
    let out = parse("sample.jpg", r#"{"max_display": 5}"#);
    assert_eq!(out["display"]["Model"], "Exif …");
}

#[test]
fn an_image_without_exif_reports_an_error() {
    let out = parse("no-exif.jpg", "");
    assert_eq!(out["ok"], false);
    assert_eq!(out["format"], "jpeg");
    assert!(out["error"].as_str().unwrap().contains("No Exif data"));
}

#[test]
fn garbage_input_reports_an_error_instead_of_panicking() {
    let out: Json = serde_json::from_slice(&read_exif(b"not an image at all", b"")).unwrap();
    assert_eq!(out["ok"], false);
    assert_eq!(out["format"], "unknown");
    assert!(out["error"].is_string());
}

#[test]
fn empty_input_reports_an_error() {
    let out: Json = serde_json::from_slice(&read_exif(b"", b"")).unwrap();
    assert_eq!(out["ok"], false);
}
