//! Native tests for the JSON the plugin hands back to Typst.

use serde_json::Value as Json;
use typst_exif_plugin::read_exif;

fn parse(name: &str, options: &str) -> Json {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../tests/assets/");
    let data = std::fs::read(format!("{path}{name}")).expect("fixture is generated by mkfixtures");
    serde_json::from_slice(&read_exif(&data, options.as_bytes())).expect("plugin returns JSON")
}

fn fields(name: &str) -> Vec<Json> {
    let out = parse(name, "");
    assert_eq!(out["ok"], true, "{}", out["error"]);
    out["fields"]
        .as_array()
        .expect("fields is an array")
        .clone()
}

fn field(name: &str, tag: &str) -> Json {
    fields(name)
        .into_iter()
        .find(|f| f["tag"] == tag)
        .unwrap_or_else(|| panic!("no {tag} field in {name}"))
}

#[test]
fn reads_the_jpeg_fixture() {
    let fields = fields("sample.jpg");
    assert_eq!(fields.len(), 29);
    assert_eq!(field("sample.jpg", "Make")["value"], "Typst");
    assert_eq!(field("sample.jpg", "Model")["value"], "Exif Fixture Camera");
    assert_eq!(field("sample.jpg", "Orientation")["value"], 1);
    assert_eq!(field("sample.jpg", "PixelXDimension")["value"], 16);
}

#[test]
fn reads_the_png_fixture() {
    assert_eq!(fields("sample.png"), fields("sample.jpg"));
}

#[test]
fn rationals_keep_numerator_and_denominator() {
    assert_eq!(
        field("sample.jpg", "ExposureTime")["value"],
        json(&[1, 200])
    );
    assert_eq!(field("sample.jpg", "FNumber")["value"], json(&[28, 10]));
}

#[test]
fn multi_valued_fields_stay_arrays() {
    let latitude = field("sample.jpg", "GPSLatitude");
    assert_eq!(latitude["count"], 3);
    assert_eq!(
        latitude["value"],
        serde_json::json!([[48, 1], [8, 1], [4123, 100]])
    );
    assert_eq!(field("sample.jpg", "GPSLatitudeRef")["value"], "N");
}

#[test]
fn fields_carry_their_ifd_and_type() {
    let make = field("sample.jpg", "Make");
    let mut keys: Vec<_> = make.as_object().unwrap().keys().cloned().collect();
    keys.sort();
    assert_eq!(keys, ["count", "ifd", "number", "tag", "type", "value"]);
    assert_eq!(make["ifd"], "primary");
    assert_eq!(make["type"], "ascii");
    assert_eq!(make["count"], 1);
    assert_eq!(make["number"], 271);

    assert_eq!(field("sample.jpg", "GPSLatitude")["ifd"], "gps");
    assert_eq!(field("sample.jpg", "DateTimeOriginal")["ifd"], "exif");
    assert_eq!(field("sample.jpg", "Orientation")["type"], "short");
}

#[test]
fn fields_come_in_file_order() {
    let order: Vec<_> = fields("sample.jpg")
        .iter()
        .map(|f| f["ifd"].as_str().unwrap().to_owned())
        .collect();
    let mut deduped = order.clone();
    deduped.dedup();
    assert_eq!(deduped, ["primary", "exif", "gps"]);
}

#[test]
fn max_values_truncates_long_fields() {
    let out = parse("sample.jpg", r#"{"max_values": 2}"#);
    let latitude = out["fields"]
        .as_array()
        .unwrap()
        .iter()
        .find(|f| f["tag"] == "GPSLatitude")
        .unwrap()
        .clone();
    assert_eq!(latitude["value"], serde_json::json!([[48, 1], [8, 1]]));
    assert_eq!(latitude["count"], 3, "the real length stays available");
}

#[test]
fn an_image_without_exif_reports_an_error() {
    let out = parse("no-exif.jpg", "");
    assert_eq!(out["ok"], false);
    assert!(out["error"].as_str().unwrap().contains("No Exif data"));
}

#[test]
fn garbage_input_reports_an_error_instead_of_panicking() {
    let out: Json = serde_json::from_slice(&read_exif(b"not an image at all", b"")).unwrap();
    assert_eq!(out["ok"], false);
    assert!(out["error"].is_string());
}

#[test]
fn empty_input_reports_an_error() {
    let out: Json = serde_json::from_slice(&read_exif(b"", b"")).unwrap();
    assert_eq!(out["ok"], false);
}

fn json(values: &[i64]) -> Json {
    Json::Array(values.iter().map(|v| (*v).into()).collect())
}
